### ISSUE TITLE
While overlay is shown, still able to zoom other images in viewport. Strange behavior follows.

### ISSUE THREAD

**Issue by alexjacque** [fat/zoom.js#10]
If there are multiple images with the zoom ability applied within the viewport, they can continue to be clicked and zoomed while the overlay is open for another image already if they happened to be below the overlay but not beneath the zoomed image (i.e. the white overlay doesn't prevent clicks from being registered with images below).

If this happens, the previous zoomed image does somewhat return to it's position, but it does not scale back down properly, and if you click it again the scale is compounded.

Successfully duplicated the problem in Safari 8.0.3, Chrome 42.0.2311.135, and Firefox 37.0.2. 

![Click, zoom, scale problem.](http://i.imgur.com/lZff0ek.gif)

**Comment by tjisousa** [comment]
@fat @alexjacque Hi guys, pushed a fix for this little issue. :+1:

**Comment by fat** [comment]
should be fixed, thanks
