### ISSUE TITLE
Support for Chrome on Android

### ISSUE THREAD

**Issue by fer-ri** [fat/zoom.js#14]
Hi, 

i've try in chrome for android, but its not work.. any idea?

Thanks

**Comment by fat** [comment]
Hm… it works in my android emulator, but i totally believe you that it's busted.

Unfortunately I don't have an android testing device… maybe if I leave this issue open someone will swoop in and save the day :ok_hand:

**Comment by Rkallenkoot** [comment]
Demo page works for me on Chrome 42 and 43. :thumbsup:

Even worked in the default browser android 4.4.2 :ok_woman:

**Comment by fer-ri** [comment]
Ah yes, demo page works on Chrome for Android ..

But strange, when i put in page with bootstrap css, then suddenly zoom not works anymore ..

this is my codepen 

http://codepen.io/ghprod/pen/aOdpRp

Any idea?

Thanks :)

**Comment by Panya** [comment]
@ghprod you don't include `zoom.js` properly. See this url: `http://fat.github.io/zoom.js/js/zoom.jss` (double **s**)

**Comment by fer-ri** [comment]
@Panya , ah my bad, some typo ..

ok case closed :)

Thanks a lot .. :D
