### ISSUE TITLE
What about 1 file for all distribution

### ISSUE THREAD

**Issue by f0rmat1k** [fat/zoom.js#17]
There are not many styles to make them into a css file. What about move styles into js file as inline styles to simplify of using and distribution? I could send a pull request.

**Comment by zslabs** [comment]
Eh - I'm a proponent for leaving it as a single CSS file and let the user decide what they want to do. I personally can easily import that CSS file as a Less import and have it compile with everything else.

**Comment by f0rmat1k** [comment]
Ok
