### ISSUE TITLE
The cursor bug

### ISSUE THREAD

**Issue by nroman** [fat/zoom.js#19]
If I don't move cursor and just click twice on the image the cursor would be with wrong state. Like '+' would be '+' always whatever I do - zoom in or out. The cursor is not changing the state until you do not change the position of it/

**Comment by hollton** [comment]
I don't have the situation you said.But sometimes it would delay 2 or 3 seconds to change the cursor's state.But I think It doesn't matter.

**Comment by fat** [comment]
yeah this is a browser bug – not much we can do on our end – same thing on medium.com

**Comment by fat** [comment]
if you happen to come up with something, please open a pr, thanks!

**Comment by nielthiart** [comment]
On Chrome v42 you can force scheduleCursorUpdate by changing the cursor style of an element's ancestors. See http://stackoverflow.com/a/30176890/121889 for a working demo.
