### ISSUE TITLE
Window size bug

### ISSUE THREAD

**Issue by nroman** [fat/zoom.js#20]
If you make the browser's window size less than the minimum size of the image  after you try to zoom in the image it would be zoom out

**Comment by fat** [comment]
heh sorry i dont quite follow - that sentence was a mouthful

**Comment by brmullikin** [comment]
I think what is meant is that if the image is larger than the viewport then zoom.js will scale the image to the size of the viewport, thus making it smaller. 

I noticed this first when having developer tools open on the page (which severely limits the height). I suppose the same would happen with a non-responsive page when the browser is made narrow.

I would think this isn't a bug though, but an expected effect.

**Comment by nroman** [comment]
Yes, brmullikin answered correctly. Sorry, I had no idea about the user expectations in this case. So if it is as expected - please, close this bug.

Just for instance - the video:
https://github.com/nroman/tmp/blob/master/zoomBugWindowSize.wmv?raw=true

From my side as a user I expected to see the bigger size of an image to see the details of it. But if you say zoom.js is working in the way you said I'm ok with it. and this is not a bug.

**Comment by fat** [comment]
ah yep, this is expected :+1:
