### ISSUE TITLE
No support for users without a meta key?

### ISSUE THREAD

**Issue by ghost** [fat/zoom.js#23]

**Comment by jdreesen** [comment]
There was a discussion on this topic here #3 
It seems that at least windows doesn't have a meta key and thus isn't supported atm :/

**Comment by ghost** [comment]
I've read the discussion - my keyboard has the "⊞" key, but it cannot be picked up by my browser since it's a OS specific key in Linux (Debian at least).
It's not even a windows issue, it's a non-OSX issue. Linux, BSD, and Windows users will all have this.

**Comment by evanfuture** [comment]
What key do you hold down while clicking a link so that it opens in a new tab?

**Comment by jdreesen** [comment]
On Windows I use `ctrl` for this.

**Comment by evanfuture** [comment]
Right, the problem is then that on windows, the Meta key is the Windows key, which doesn't really do what's expected. http://api.jquery.com/event.metakey/

**Comment by nofxx** [comment]
There's no meta key on linux (according to jquery)...
Listen to 'ctrl' key code? Won't hurt on OSX and fixes win and linux.

**Comment by evanfuture** [comment]
Well, on OSX the ctrl key brings up the contextual menu.... 

I suppose checking for user agent is too big a footprint?

**Comment by fat** [comment]
yeah don't want to do ctrl key because of the menu problem

**Comment by arjshiv** [comment]
@fat - Thanks for making this awesome plugin. I came across this as I was looking at trending Javascript projects on GitHub. 

My understanding is that e.ctrlKey does;t actually fire when you use the ctrl key on Mac - so you are safe to use metaKey for Mac and ctrl key for Windows. I actually use this in one of my corporate applications - metaKey+click on Mac, ctrl+click on Windows. A quick debug+inspect in safari when clicking on the image in http://fat.github.io/zoom.js/ also shows that e.ctrlKey doesn't fire when I use ctrl+click on a Mac. If this is good with you, I'd love to pull and make the enhancement.

**Comment by fat** [comment]
fixed!

**Comment by jdreesen** [comment]
nice, thx! :)
