### ISSUE TITLE
Horizontal scroll on window resize

### ISSUE THREAD

**Issue by korywka** [fat/zoom.js#25]
1. open full width example page
2. click on image
3. resize window => scroll appears

screenshot: https://www.dropbox.com/s/v6fvz8ffb2hn72s/Screenshot-2015-05-13-14.50.00.png?dl=0

**Comment by korywka** [comment]
btw no such behaviour here: https://medium.com/designing-medium/image-zoom-on-medium-24d146fc0c20

**Comment by fat** [comment]
That's just because the zoomed image tracks the default image's size - it's the same behavior on medium.

Not really worried about that issue being caused by someone resizing their window extra small, once they've already zoomed an image. doesn't seem like it would happen much, if at all
