### ISSUE TITLE
Bower support please

### ISSUE THREAD

**Issue by elgs** [fat/zoom.js#28]
Bower support please. Thanks.

**Comment by fat** [comment]
> zoom.js should (in theory) work in all relevant browsers. If not, create an issue! Thanks!

**Comment by elgs** [comment]
@fat you misunderstood what I meant. `zoom.js` is great, and I hope to use it in my project. I hope to install it using `bower install zoom.js --save` instead of copying the files manually in my project. The advantage is I can easily get it updated using a single bower command. So if you wish to support bower, what you need to do is create a tag for your project, and register it with bower. Thanks.

**Comment by fat** [comment]
I created bower - i know how it works ;)

**Comment by fat** [comment]
oh but i did misread your issue!

**Comment by fat** [comment]
here's my relevant response https://github.com/fat/zoom.js/pull/2 - sorry about the misunderstanding
