### ISSUE TITLE
Holding META key should open the full-size image as a direct link in a new tab

### ISSUE THREAD

**Issue by rauchg** [fat/zoom.js#3]
eg: ⌘

This is also a neat workaround to the situation where the real image size exceeds the viewport's.

**Comment by fat** [comment]
you owe me, atleast, 5% of your company

**Comment by jdreesen** [comment]
Sadly, your fix in b9d978ea doesn't work for me in FF37 and Chrome 43beta on Win7. Maybe I'm just using the wrong `meta` key? I tried with `shift`, `ctrl`, `alt`, `win` but nothing works (even in the [jQuery demo](https://api.jquery.com/event.metakey/)). So, which one do I have to use?

**Comment by fat** [comment]
we use this property in jquery: http://api.jquery.com/event.metakey/

Honestly not sure what it maps to on win7 – maybe you don't have a metakey?

**Comment by jdreesen** [comment]
I already checked the jquery property and it doesn't work. Seems that windows has no `metakey`, but it's not that easy to find any information about that key.

**Comment by rauchg** [comment]
I think on Windows it's ctrl ?

**Comment by jdreesen** [comment]
I thought that too, but it doesn't work - at least for me.

**Comment by cvrebert** [comment]
[MouseEvent.metaKey](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/metaKey):

> Note: On Macintosh keyboards, this is the command key (⌘). On Windows keyboards, this is the Windows key (⊞).

**Comment by jdreesen** [comment]
Did you try it? Does it work for you?
