### ISSUE TITLE
Problem with IE 11, image not centering

### ISSUE THREAD

**Issue by mshatikhin** [fat/zoom.js#32]
Problem with IE 11, image not centering.

![problem](https://cloud.githubusercontent.com/assets/1788385/7755578/8bcc611a-000e-11e5-992d-3c578d65df83.PNG)

**Comment by fat** [comment]
hm… i don't have a way to test i.e. 11 right now - if you  (or anyone else) wants to debug, that would be rad.

i'll leave the issue open

**Comment by fat** [comment]
also note, i did merge an i.e. fix, which may address this

**Comment by sirakoff** [comment]
I updated to the latest and it worked!

**Comment by fat** [comment]
perfect
