### ISSUE TITLE
Link to zoom.js must be at end of doc not in head

### ISSUE THREAD

**Issue by carmi** [fat/zoom.js#34]
I was having a bit of trouble getting zoom.js to work, and it seemed like the final reason was I was placing my link to zoom.js in <head> not at the end of the body -- after the img's with the data-action="zoom". My understanding (could be wrong) is that when the script is loaded it immediately adds a on click listener to each of those elements. So you can't place it in the head. This makes sense, but if correct, I think adding a but of clarification to docs would be helpful. I'll add those clarifications to the docs, but wanted to check that this was correct before sending a PR with the changes. Thanks!

**Comment by bravokiloecho** [comment]
I think this is right too. I've submitted a pull request (#31) that would resolve this issue by initialising the plugin within a document ready listener.

**Comment by carmi** [comment]
Oh yeah, dur! that's a smarter way to handle this! Thanks @bravokiloecho

**Comment by fat** [comment]
this was fixed, thanks
