### ISSUE TITLE
IE8 - Object doesn't support property or method 'addEventListener'

### ISSUE THREAD

**Issue by rssfrncs** [fat/zoom.js#36]
Object doesn't support property or method 'addEventListener'

File: zoom.js, Line: 47, Column: 5

Condition: Click on any image in IE8 above error occurs.

**Comment by rssfrncs** [comment]
Perhaps use "attachEvent("onclick", ...)" if browser does not support "addEventListener"?

**Comment by fat** [comment]
doesn't support ie8
