### ISSUE TITLE
Add JQuery dependencie and transition.js to the repository

### ISSUE THREAD

**Issue by Johann-S** [fat/zoom.js#39]
- I think it would be interesting to add that zoom.js depend on JQuery and users have to
  include first JQuery on the `How` section of the `README.md`
- It would be usefull to add transition.js to this repository to merge transition.js and zoom.js on your `compress` grunt task.

**Comment by fat** [comment]
hm… the first line of the docs reads: 

> A simple jQuery plugin for image zooming;

I don't want to bundle transition.js because it's a separate plugin and should really be added to your asset pipeline :+1:

**Comment by Johann-S** [comment]
Ok thank you for your answers
