### ISSUE TITLE
Support anchor to image link

### ISSUE THREAD

**Issue by klihelp** [fat/zoom.js#46]
Is it possible to support load small image normally and have an anchor to large image?
`<a href="large.jpg">
    <img src="small.jpg"></img>
</a>`

**Comment by f-liva** [comment]
This would be a great improvement for the plugin! +1

**Comment by kingdido999** [comment]
I wrote a similar image zooming library that supports zooming in with a large image source: https://github.com/kingdido999/zooming

Please let me know what you think:)

**Comment by daxhns** [comment]
@kingdido999 Good work!

**Comment by klihelp** [comment]
https://github.com/kingdido999/zooming
