### ISSUE TITLE
No "wow" on linux

### ISSUE THREAD

**Issue by dawadam** [fat/zoom.js#50]
On Linux, when the CTRL key is maintained before clicking, nothing happens ...
Only with "data-original" attribute, works without.

**Comment by fat** [comment]
hm… did you try cmd key?

**Comment by dawadam** [comment]
Yes, i touched it...
Works not only with "data-original" attribute, on chromium and firefox.

**Comment by bookercodes** [comment]
I am running FF on Ubuntu and it works fine here...

**Comment by dawadam** [comment]
All is OK, I think I did not understand the operating principle.
