### ISSUE TITLE
Proposal : thumbnail / original

### ISSUE THREAD

**Issue by dawadam** [fat/zoom.js#51]
Why not allow to differentiate the thumbnail of the zoomed photo?
For example enable a tiny or cropped thumbnail and display the original on zooming.

**Comment by fat** [comment]
this is a duplicate proposal - it's a bit of a pain and complicates the plugin a great deal - which is why i didn't write it here… open to pr's tho

**Comment by dawadam** [comment]
Ok.
Sorry for duplicate.
