### ISSUE TITLE
No transition when zooming out

### ISSUE THREAD

**Issue by sexsugar** [fat/zoom.js#63]
When i zoom in the image i've got the smooth transition that's supposed to happen, but when i zoom out there's no transition, which is kinda lame :-/ 

Someone's got an idea why and how to fix this ?

Thanks a lot, great plugin

**Comment by spinningarrow** [comment]
Could you post a link to a CodePen or something? Perhaps some custom CSS is interacting badly.
On the demo page, the transition seems to be working fine when zooming out.

**Comment by sexsugar** [comment]
Thanks for the answer!

You can see what I’m struggling with here : http://www.jonathanllense.com/2015/12/01/la-relation-entre-x-y/ http://www.jonathanllense.com/2015/12/01/la-relation-entre-x-y/

Everything works fine when zooming in but when zooming out …

Georges Chaulet

georges@uplaod.fr mailto:georges@uplaod.fr

uplaod.fr http://www.uplaod.fr/

**Comment by heavybeard** [comment]
Hi @sexsugar,
your problem is on Safari, right?

**Comment by theresama** [comment]
Make sure that you're also linking bootstrap's transition.js

**Comment by ElegantSudo** [comment]
@theresama it looks like he solved his problem and removed the hosted code. As far as I can tell, this issue should be closed.

**Comment by sexsugar** [comment]
sorry, forgot to update it!
it was resolved by simply setting a width to the images (which i was not aware was necessary)
thanks anyway : )

**Comment by ElegantSudo** [comment]
@sexsugar ok, you should close the issue now.
