### ISSUE TITLE
Demo buggy in Safari iOS

### ISSUE THREAD

**Issue by simevidas** [fat/zoom.js#7]
I’ve tried your demo (http://fat.github.io/zoom.js/) in Safari/iOS 8 on an iPhone. Tap-to-zoom works on the first image, but not for the second image which immediately “closes”. 

My wild guess is that this bug is caused by the lack of a viewport meta tag in the demo. Could you add 

``` html
<meta name="viewport" content="width=device-width,initial-scale=1">
```

and test if the bug goes away?

**Comment by fat** [comment]
ah good call, cleaned it up for ya. thanks for filing!
