### ISSUE TITLE
zoom on mobile

### ISSUE THREAD

**Issue by fabiocaccamo** [fat/zoom.js#75]
Since generally on mobile devices images are already full-width you will not see the image larger when zooming.

A nice solution to this behavior would be to zoom the image to fill the device viewport (without upscaling the image) and having the possibility to pan it.

If you have interest to add this feature we can discuss about it more specifically.

**Comment by heavybeard** [comment]
Great Idea! +1

**Comment by alessandrogomba** [comment]
+1

**Comment by oninross** [comment]
+1
