### ISSUE TITLE
Append element to document body instead of wrapping the photo

### ISSUE THREAD

**Issue by ElegantSudo** [fat/zoom.js#77]
There should be an easy and performant way to append the wrapper with the image to the document body, with the exact positioning of the previous photo (positioned absolute to body, top and left values). 

This would solve the `overflow: hidden` a lot of users are currently having because the wrapper would be positioned relative to the body element.

**Comment by ElegantSudo** [comment]
@fat what are your thoughts on this? Maybe there's a smarter way to design our apps or work around this issue.

**Comment by ElegantSudo** [comment]
@fat hey, I'm not sure if you saw my post up there. Let me know what you think.

**Comment by ElegantSudo** [comment]
@alisonmonteiro what are your thoughts on this issue?

**Comment by ElegantSudo** [comment]
Fixed in forked repo. This repo is unmaintained garbage now.

**Comment by Ilshidur** [comment]
Can you link the forked repo please ?

**Comment by ElegantSudo** [comment]
@Ilshidur it's linked above in the merged commit by spinningarrow.

**Comment by Ilshidur** [comment]
Thank you !
