### ISSUE TITLE
If you click on the image and then resize the window you are ending up in a "bad" state.

### ISSUE THREAD

**Issue by lipis** [fat/zoom.js#8]
I think it would be better to reposition/resize the image on every resize of the window if it's in a zoomed state.

![screen shot 2015-05-07 at 08 42 34](https://cloud.githubusercontent.com/assets/125676/7509753/2b847344-f495-11e4-9c84-b16aa89da7ff.png)
![screen shot 2015-05-07 at 08 42 08](https://cloud.githubusercontent.com/assets/125676/7509754/2b858608-f495-11e4-8737-228c1903373a.png)

**Comment by fat** [comment]
hm maybe – i'm not too worried about that. People don't tend to resize their windows in the middle of a browsing session.

if it's really bothering you though, happy to review a pr
