### ISSUE TITLE
If the pic is very large, the image will zoom in

### ISSUE THREAD

**Issue by doublnt** [fat/zoom.js#86]
The image like this
> ![](http://images2015.cnblogs.com/q/161654/201705/161654-20170523223607857-1679571871.jpg)

when click use zoom.js it will zoom in ,how can I fix it ?

**Comment by doublnt** [comment]
![](https://ws4.sinaimg.cn/large/006tKfTcgy1ffwhr285t6g314616jtju.gif)

**Comment by heavybeard** [comment]
This repo is dead. I suggest you to use this one https://github.com/spinningarrow/zoom-vanilla.js/

**Comment by doublnt** [comment]
Thank you ,let me have a try
